### ISSUE TITLE
Otro profe de Lenguaje de Marcas

### ISSUE THREAD

**Issue by mat130517** [BartolomeSintes/mclibre-python#1]
Hola, buenas.
Me llamo Matias y hasta el año pasado había impartido la asignatura de LMA en un instituto de Palma de Mallorca. Tan solo decirte que tienes una muy buena colección de cursos de los cuales aprovecho algún ejercicio. ¿Cómo haces para dar tanta materia en 4h semanales? Yo daba muy poca teoría y tus cursos son bastante exhaustivos.  Si quieres tengo material en Javascript y estoy realizando ejercicios también en Python. Mi web de javascript es [www.ibserveis.com](http://www.ibserveis.com)
Te adjunto libro de ejercicios de Javascript.
[2017_Javascript_Ejercicios_1.pdf](https://github.com/BartolomeSintes/mclibre-python/files/1385043/2017_Javascript_Ejercicios_1.pdf)

**Comment by BartolomeSintes** [comment]
Hola, Matías:
Gracias por el comentario y me alegra que hayas podido aprovechar mis apuntes para tus clases.
Los apuntes incluyen mucha más materia de la que puedo dar en clase (ten en cuenta además que en la Comunidad Valenciana, donde resido, el módulo tiene sólo 3 horas semanales).  En los apuntes hay muchos temas que en algún momento he dado en clase, pero que ya no doy (en muchos casos precisamente por falta de tiempo), y hay temas que he incuido por "completitud", aunque tampoco los he dado nunca. Este año he incluido una [lección donde voy contando lo que hago en clase](http://www.mclibre.org/consultar/htmlcss/otros/clase.html) que sirva de guía a otros aprofesores o alumnos.
Los alumnos de ASIR suelen tener bastantes dificultades con la programación (o al menos esa es mi experiencia). Para reducir la dificultad del módulo de segundo en el que doy PHP, Implantación de Aplicaciones Web, en el módulo de primero LM doy un poco de Python para introducir los conceptos básicos de programación estructurada. Últimemente me he planteado la opción de adoptar JavaScript en ambos módulos, pero no tengo claro si sería una buena idea.
Gracias por el libro de JavaScript. En Internet hay mucho material, pero creo que siempre es bueno tener la referencia de algo que alguien ha usado de verdad en clase. Por eso yo incluyo en mis apuntes no sólo la teoría y los ejercicios, sino también los exámenes. 
Si me aceptas la sugerencia, lo mejor sería que también colgaras el material en GitHub, para que otros profesores pudieran aprovecharlo. Cuesta mucho tiempo preparar materiales y se quedan obsoletos rápidamente, así que creo que tenemos que hacer todo lo posible por hacerlos accesibles. 
Yo dedico mucho tiempo a preparar los apuntes y pienso que dedico poco tiempo a mis alumnos (pidiéndoles trabajos, corrigiéndoles ejercicios, etc), pero otros profesores que no necesiten preparar apuntes porque usen los míos podrán dedicarles más tiempo a sus alumnos. 
Un saludo, y espero que vuelvas pronto a dar Lenguaje de marcas
Barto
