### ISSUE TITLE
Actualizar código en ejemplos que se usa función print

### ISSUE THREAD

**Issue by EllaQuimica** [BartolomeSintes/mclibre-python#2]
Hola @BartolomeSintes 

1. En el ejemplo de sentencias condicionales if , al momento de usar la función print, se genera un error al no mostrar el número ingresado

`print(f"Ha escrito el número {numero}")`

 se soluciona con 
`print("Ha escrito el número:", numero)`

https://github.com/BartolomeSintes/mclibre-python/blob/a9eb37e506a4e28da308533d3ad6e0f6d71f7ffa/lecciones/python-if-else.html#L292

2. Ejemplo para usar Pass, tienes en la linea 997 y 1008

`print(f"Usted dice que tiene {edad} años.") `

Solución con:
`print("Usted dice que tiene", edad, "años.")`

https://github.com/BartolomeSintes/mclibre-python/blob/f1e7be942a0ea34a5b68ce63b141238c33463887/lecciones/python-if-else.html#L997

https://github.com/BartolomeSintes/mclibre-python/blob/f1e7be942a0ea34a5b68ce63b141238c33463887/lecciones/python-if-else.html#L1008

**Comment by BartolomeSintes** [comment]
Hola,
Ten en cuenta que en los apuntes utilizo siempre las cadena "f", introducidas en Python 3.6. Las cadenas "f" las explico en http://www.mclibre.org/consultar/python/lecciones/python-cadenas.html#cadenas-f
La notación antigua (que se puede seguir utilizando en Python 3.6 y posteriores la explico en http://www.mclibre.org/consultar/python/lecciones/python-obsoletos.html#print
Creo que con las cadenas "f" es mucho más fácil incluir variables en cadenas, sobre todo cuando queremos que haya caracteres unidos a los valores d elas variables, por eso la utilizo.
¿Qué versión de Python estás utilizando tú? Si es una versión anterior a Python 3.6, efectivamente te dará error (no sólo ese ejemplo, sino todos los ejemplos y las soluciones de los ejercicios). Si utilizas windows te recomiendo instalar la última versión de Python. Si utilizas una distribución Linux, es posible que puedas instalar una versión posterior a la versión 3.6 o no, depende de la distribución.
Gracias por el aviso. 
Un saludo,
Barto

**Comment by EllaQuimica** [comment]
Gracias @BartolomeSintes por tomarte el tiempo de responderme. Tienes razón, no había visto el contenido anterior de Cadenas con funciones "f", pensé que no se había explicado y que confundía a la persona que siguiera los apuntes. Gracias por todo el trabajo compilado en este proyecto!
